# Generated by Django 5.2.5 on 2025-08-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Limited edition',
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='Limited edition'),
        ),
    ]
