# Generated by Django 5.2.5 on 2025-08-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Бесплатная доставка'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
